/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Desktop;

/**
 *
 * @author Cemmy
 */
public class frmMain extends javax.swing.JFrame {

    private static void HIDE_ON_CLOSE(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mTanim = new javax.swing.JMenu();
        mPersonel = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mFirma = new javax.swing.JMenuItem();
        mKasa = new javax.swing.JMenuItem();
        mTeknik = new javax.swing.JMenu();
        mKargo = new javax.swing.JMenu();
        mRaporlar = new javax.swing.JMenu();
        mAyarlar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 814, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        mTanim.setText("Tanımlar");

        mPersonel.setText("Personel");
        mPersonel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPersonelActionPerformed(evt);
            }
        });
        mTanim.add(mPersonel);

        jMenuItem1.setText("Müşteri");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mTanim.add(jMenuItem1);

        mFirma.setText("Firma");
        mTanim.add(mFirma);

        mKasa.setText("Kasa");
        mTanim.add(mKasa);

        jMenuBar1.add(mTanim);

        mTeknik.setText("Teknik Servis");
        jMenuBar1.add(mTeknik);

        mKargo.setText("Kargo Takip ");
        jMenuBar1.add(mKargo);

        mRaporlar.setText("Raporlar");
        jMenuBar1.add(mRaporlar);

        mAyarlar.setText("Ayarlar");
        jMenuBar1.add(mAyarlar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mPersonelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPersonelActionPerformed
        frmPersonel frmPersonelTanim = new frmPersonel();
        Desktop.add(frmPersonelTanim);
        frmPersonelTanim.setVisible(true);
              
        this.setDefaultCloseOperation(3);
        //this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_mPersonelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mAyarlar;
    private javax.swing.JMenuItem mFirma;
    private javax.swing.JMenu mKargo;
    private javax.swing.JMenuItem mKasa;
    private javax.swing.JMenuItem mPersonel;
    private javax.swing.JMenu mRaporlar;
    private javax.swing.JMenu mTanim;
    private javax.swing.JMenu mTeknik;
    // End of variables declaration//GEN-END:variables
}
